##########################################################################
# 	ExpressOS
#	OS Specific Makefile
#	2021, Zachary BerryS
##########################################################################

#
#	TODO: We might use this as a 'main' makefile for various OS specific modules/drivers/applications
#	Meaning, each OS application will have its own makefile, just invoked from here
#	This allows us to create commands to basically build groups, or all of the OS applications
#	These makefile commands will then in turn be executed by the main project makefile
#